export declare function fnDebounce(): (fn: any, delayTime: any, isImediate: any, args: any) => any;
export declare function getRandomString(): string;
export declare function mkdir(filepath: any, opt?: {}): void;
export declare function chmodPath(path: any, mode: any): void;
export declare function compareVersion(v1: any, v2: any): 0 | 1 | -1;
export declare function middleware(fn: any): any;
export declare function stringify(obj: any, ignore?: any[]): string;
export declare function validValue(value: any): boolean;
export declare function checkConfig(prop: any): boolean;
export declare function loadConfig(prop: any): any;
export declare function sleep(ms: any): Promise<any>;
export declare function replaceArgsValue(argv: any, key: any, value: any): any;
export declare function getValueFromArgv(argv: any, key: any): any;
export declare function fileIsExist(filepath: any): boolean;
