export declare function getPackage(): any;
export declare function getMAC(iface: any): string;
export declare function isMAC(macAddress: any): boolean;
export declare function isFileProtocol(protocol: any): boolean;
export declare function isWebProtocol(protocol: any): boolean;
export declare function isJsProject(baseDir: any): boolean;
export declare function machineIdSync(original: any): any;
export declare function machineId(original: any): Promise<any>;
import is = require("./is");
export { is };
